CREATE TABLE T_REGISTROS_GASTO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DATA_GASTO DATE,
	VALOR_GASTO DECIMAL(10,2),
	ID_TIPO_GASTO INT,
	ID_LOCAL_GASTO INT,
	ID_TIPO_PAGAMENTO INT,
	ID_USUARIO_PAGOU INT,
	ID_METODO_PAGAMENTO INT,
	ID_CARTAO INT,
	OBSERVACOES VARCHAR(100)
);

CREATE TABLE T_TIPO_GASTO (
	ID_TIPO_GASTO INT IDENTITY(1,1) PRIMARY KEY,
	NOME_TIPO_GASTO VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE T_LOCAL_GASTO (
	ID_LOCAL_GASTO INT IDENTITY(1,1) PRIMARY KEY,
	NOME_LOCAL_GASTO VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE T_TIPO_PAGAMENTO (
	ID_TIPO_PAGAMENTO INT IDENTITY(1,1) PRIMARY KEY,
	NOME_TIPO_PAGAMENTO VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE T_USUARIO_PAGOU (
	ID_USUARIO_PAGOU INT IDENTITY(1,1) PRIMARY KEY,
	NOME_USUARIO_PAGOU VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE T_METODO_PAGAMENTO (
	ID_METODO_PAGAMENTO INT IDENTITY(1,1) PRIMARY KEY,
	NOME_METODO_PAGAMENTO VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE T_CARTAO (
	ID_CARTAO INT IDENTITY(1,1) PRIMARY KEY,
	NOME_CARTAO VARCHAR(100) NOT NULL UNIQUE,
	BANDEIRA_CARTAO VARCHAR(100) NOT NULL UNIQUE
);


-- Relaciona o tipo do gasto
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_TIPO_GASTO
FOREIGN KEY (ID_TIPO_GASTO)
REFERENCES T_TIPO_GASTO(ID_TIPO_GASTO);

-- Relaciona o local do gasto
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_LOCAL_GASTO
FOREIGN KEY (ID_LOCAL_GASTO)
REFERENCES T_LOCAL_GASTO(ID_LOCAL_GASTO);

-- Relaciona o tipo de pagamento
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_TIPO_PAGAMENTO
FOREIGN KEY (ID_TIPO_PAGAMENTO)
REFERENCES T_TIPO_PAGAMENTO(ID_TIPO_PAGAMENTO);

-- Relaciona o usuário que pagou
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_USUARIO_PAGOU
FOREIGN KEY (ID_USUARIO_PAGOU)
REFERENCES T_USUARIO_PAGOU(ID_USUARIO_PAGOU);

-- Relaciona o método de pagamento
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_METODO_PAGAMENTO
FOREIGN KEY (ID_METODO_PAGAMENTO)
REFERENCES T_METODO_PAGAMENTO(ID_METODO_PAGAMENTO);

-- Relaciona o cartão
ALTER TABLE T_REGISTROS_GASTO
ADD CONSTRAINT FK_CARTAO
FOREIGN KEY (ID_CARTAO)
REFERENCES T_CARTAO(ID_CARTAO);