SELECT 
	RGA.ID,
	RGA.DATA_GASTO,
	RGA.VALOR_GASTO,
	TGA.NOME_TIPO_GASTO,
	LGA.NOME_LOCAL_GASTO,
	TPA.NOME_TIPO_PAGAMENTO,
	USU.NOME_USUARIO_PAGOU,
	MPA.NOME_METODO_PAGAMENTO,
	CAR.NOME_CARTAO
FROM T_REGISTROS_GASTO RGA
	INNER JOIN T_TIPO_GASTO TGA
	ON RGA.ID_TIPO_GASTO = TGA.ID_TIPO_GASTO
	INNER JOIN T_LOCAL_GASTO LGA
	ON RGA.ID_LOCAL_GASTO = LGA.ID_LOCAL_GASTO
	INNER JOIN T_TIPO_PAGAMENTO TPA
	ON RGA.ID_TIPO_PAGAMENTO = TPA.ID_TIPO_PAGAMENTO
	INNER JOIN T_USUARIO_PAGOU USU
	ON RGA.ID_USUARIO_PAGOU = USU.ID_USUARIO_PAGOU
	INNER JOIN T_METODO_PAGAMENTO MPA
	ON RGA.ID_METODO_PAGAMENTO = MPA.ID_METODO_PAGAMENTO
	INNER JOIN T_CARTAO CAR
	ON RGA.ID_CARTAO = CAR.ID_CARTAO
WHERE RGA.DATA_GASTO BETWEEN '2025-07-04' AND '2025-07-26' -- Preencher com as datas inicio e fim

